USE [master]
GO

/****** Object:  Database [HMOCoronaDB]    Script Date: 28/03/2024 19:00:08 ******/
CREATE DATABASE [HMOCoronaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HMOkoronaDB', FILENAME = N'C:\Users\User\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\HMOkoronaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HMOkoronaDB_log', FILENAME = N'C:\Users\User\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\HMOkoronaDB.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HMOCoronaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HMOCoronaDB] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [HMOCoronaDB] SET ANSI_NULLS ON 
GO

ALTER DATABASE [HMOCoronaDB] SET ANSI_PADDING ON 
GO

ALTER DATABASE [HMOCoronaDB] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [HMOCoronaDB] SET ARITHABORT ON 
GO

ALTER DATABASE [HMOCoronaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HMOCoronaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [HMOCoronaDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [HMOCoronaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [HMOCoronaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HMOCoronaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HMOCoronaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET RECOVERY FULL 
GO

ALTER DATABASE [HMOCoronaDB] SET  MULTI_USER 
GO

ALTER DATABASE [HMOCoronaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HMOCoronaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HMOCoronaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HMOCoronaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HMOCoronaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HMOCoronaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HMOCoronaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HMOCoronaDB] SET  READ_WRITE 
GO

